### ISSUE TITLE
walrus818 has WKT2 comment on CRS, but still expect warning

### ISSUE THREAD

**Issue by rsbivand** [Trackage/trip#45]
Because the input object also has a WKT2 comment, no warning is given in test-algos.R, lines 27, 29 or 39. To get previous behaviour back, add `comment(slot(tr, "proj4string")) <- NULL` or similar in the test script. This for my current **sp** fork on `rsbivand/sp`, and possibly development **rgdal** on R-Forge.

**Comment by mdsumner** [comment]
thank you
